-- Prova Par
-- Nome: Vinicius Escame dos Santos
-- Status da atividade: Funcionando

/*
select table_name from all_tables where owner = 'SYSTEM'
AND TABLE_NAME not like 'LOG%'
AND TABLE_NAME not like 'ROLL%'
AND TABLE_NAME not like 'OL$%'
AND TABLE_NAME not like 'AQ$%'
AND TABLE_NAME not like 'MVIEW%'
AND TABLE_NAME not like 'SCH%';
*/

/*
CRIAR TRIGGER PARA LIMITAR A INCLUSAO DE HORARIO PARA TURMAS CUJO PROFESSOR
TENHA UM TITULO DE NOME 'ESPECIALISTA'. UTILIZE PELO MENOS UM NATURAL JOIN.
*/

    SELECT DISTINCT UPPER(NOMETIT)
    FROM PROFTURMA
 NATURAL JOIN PROFES  SOR
 NATURAL JOIN TITULACAO WHERE NUMDISC = 2;

UPDATE TITULACAO SET NOMETIT = 'Especialista' WHERE CODTIT = 2;
SELECT *
   -- INTO V_TITULO
    FROM PROFTURMA
NATURAL JOIN TURMA
NATURAL JOIN PROFESSOR
NATURAL JOIN TITULACAO WHERE NUMDISC = 1;

SELECT UPPER(CODDEPTO) FROM HORARIO;
SELECT * FROM TURMA;
SELECT * FROM PROFTURMA
NATURAL JOIN TURMA
NATURAL JOIN PROFESSOR
NATURAL JOIN TITULACAO;
select * from titulacao;
SELECT * FROM PROFTURMA;
SELECT * FROM horario;

DELETE FROM HORARIO WHERE ANOSEM = 20021 AND CODDEPTO = 'PROG1';
DELETE FROM HORARIO WHERE ANOSEM = 20021 AND CODDEPTO = 'GEST1';

INSERT INTO HORARIO VALUES(20021, 'PROG1', 1, 'P1', 4, 12, 103, 43566, 4);
INSERT INTO HORARIO VALUES(20021, 'GEST1', 2, 'G1', 2, 7, 101, 34567, 2);

CREATE OR REPLACE TRIGGER TR_LIMITA_HORARIO
BEFORE UPDATE OR INSERT ON HORARIO
FOR EACH ROW
ENABLE
DECLARE
  V_TITULO VARCHAR(35);
BEGIN

  SELECT DISTINCT UPPER(NOMETIT)
    INTO V_TITULO
    FROM PROFTURMA
 NATURAL JOIN PROFESSOR
 NATURAL JOIN TITULACAO WHERE NUMDISC = :NEW.NUMDISC;

  IF V_TITULO = 'ESPECIALISTA' THEN
      RAISE_APPLICATION_ERROR(-20000, 'Nao podemos inserir horarios em que o professor e especialista');
   END IF;
   EXCEPTION
      WHEN NO_DATA_FOUND THEN
      DBMS_OUTPUT.PUT_LINE(V_TITULO);
END;
/

